export const correctAnswers: Record<string, string[]> = {
  "1": ["HyperText Markup Language"],
  "2": ["Cascading Style Sheets"],
  "3": ["React", "Angular", "Vue"],
  "4": ["Application Programming Interface"],
  "5": ["MongoDB"],
  "6": ["HTML", "CSS", "JavaScript"],
  "7": ["object"],
  "8": ["PUT"],
  "9": ["443"],
  "10": ["MongoDB", "Redis", "Cassandra"],
  "11": ["Building user interfaces"],
  "12": ["The object that owns the current code"],
  "13": ["Add static typing to JavaScript"],
  "14": ["Vue", "Svelte"],
  "15": ["There is none"],
};
